#######################################
# Website title
title: "🚀 AutoSite"


#######################################
# Configurations

# Base URL (use "/"" for root, or use "/foldername" for subdirectories)
base_url: "/site"

# Assets configuration
assets:
  source_dir: "assets"

# Theme customization
theme:
  font_family: "'Red Hat Mono', 'Courier New', monospace"
  primary_color: "#a1752f"
  contrast_color: "#300175"


#######################################
# Website Pages
homepage: "content/home.md"

pages:
  - title: "About"
    path: "content/about.md"

  - title: "Blog"
    path: "content/blog"


  - title: "GitHub"
    path: "https://github.com"
